# ============================================================
# Academic Codex – Repository Registry
# Source of truth - GRAD
# ============================================================

repos:

  - org: Quantum-Computing-Research
    name: quantum-error-mitigation
    id: Quantum Error Mitigation
    title: "Research"
    academic_level: graduate
    academic_area: 
    academic_school: 
    status: 
    completed_on: 
    site_hero_image: quantum-error-mitigation.png
    site_description:
    readme_tagline:
    readme_cta_text: "Open full course website."
    readme_theme: minimal

  - org: Quantum-Computing-Research
    name: quantum-algorithms
    id: Quantum Algorithms
    title: "Research"
    academic_level: graduate
    academic_area: 
    academic_school: 
    status: 
    completed_on: 
    site_hero_image: quantum-algorithms.png
    site_description:
    readme_tagline:
    readme_cta_text: "Open full course website."
    readme_theme: minimal

  - org: Quantum-Computing-Research
    name: quantum-learning
    id: Quantum Learning
    title: "Research"
    academic_level: graduate
    academic_area: 
    academic_school: 
    status: 
    completed_on: 
    site_hero_image: quantum-learning.png
    site_description:
    readme_tagline:
    readme_cta_text: "Open full course website."
    readme_theme: minimal

  - org: Quantum-Computing-Research
    name: Batalha-Naval-Quantica
    id: Batalha Naval Quantica
    title: "Game"
    academic_level: graduate
    academic_area: 
    academic_school: 
    status: 
    completed_on: 
    site_hero_image: batalha-naval-quantica.png
    site_description:
    readme_tagline:
    readme_cta_text: "Open full course website."
    readme_theme: minimal